package com.cleanroommc.lwjgly.tool;

import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.LdcInsnNode;
import org.objectweb.asm.tree.MethodNode;

import java.io.BufferedWriter;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;

public final class ProblemsDoc {

    public static void write(Path file, Map<String, Delta.ClassDelta> deltas, ApiIndex lwjgl2, ApiIndex lwjgl3, Built built) throws IOException {
        Map<String, List<Delta.MethodDelta>> unservable = new TreeMap<>();
        Map<String, List<Delta.MethodDelta>> manual = new TreeMap<>();
        int implemented = 0;
        for (Delta.ClassDelta delta : deltas.values()) {
            String owner = delta.internalName();
            List<Delta.MethodDelta> none = delta.methods().stream()
                    .filter(m -> m.fix() == Delta.Fix.NO_TARGET)
                    .filter(m -> !works(built, lwjgl3, owner, m))
                    .toList();
            if (!none.isEmpty()) {
                unservable.put(owner.replace('/', '.'), none);
            }
            List<Delta.MethodDelta> hand = delta.methods().stream()
                    .filter(m -> m.fix() == Delta.Fix.MANUAL)
                    .filter(m -> !works(built, lwjgl3, owner, m))
                    .toList();
            if (!hand.isEmpty()) {
                manual.put(owner.replace('/', '.'), hand);
            }
            implemented += (int) delta.methods().stream()
                    .filter(m -> m.fix() == Delta.Fix.NO_TARGET || m.fix() == Delta.Fix.MANUAL)
                    .filter(m -> works(built, lwjgl3, owner, m))
                    .count();
        }
        if (built != null) {
            System.out.println(file + ": " + implemented + " member(s) the diff could not serve have a handwritten body and are not listed");
        }

        Map<String, List<String>> rewrites = new LinkedHashMap<>();
        for (Delta.ClassDelta delta : deltas.values()) {
            if (delta.bucket() == Delta.Bucket.SHIM && delta.shimSource() == Delta.ShimSource.REWRITE
                    && ApiIndex.isNameable(lwjgl2.get(delta.internalName()))
                    && !started(lwjgl2, lwjgl3, built, delta.internalName())) {
                rewrites.put(delta.internalName().replace('/', '.'), delta.rejections());
            }
        }

        try (BufferedWriter out = Files.newBufferedWriter(file)) {
            out.write("""
                    # Problems
                    
                    Generated by `./gradlew problemsDoc`. Do not edit by hand.
                    
                    LWJGLY's promise is that an LWJGL 2 call site never fails to link.
                    Where LWJGL 3 has no equivalent, the member still exists with the right signature and throws
                    `UnsupportedOperationException` when called, and it is listed here.
                    A `NoSuchMethodError` would be a bug in LWJGLY.
                    
                    Read from the compiled classes, not from the API diff. The diff describes what the
                    generator can do on its own, and a member it cannot serve may still have a handwritten
                    body.
                    
                    """);

            out.write("## Methods with no LWJGL 3 counterpart\n\n");
            out.write("LWJGL 3 declares no method of this name on the class at all. These throw.\n\n");
            if (unservable.isEmpty()) {
                out.write("_None._\n\n");
            } else {
                unservable.forEach((owner, methods) -> {
                    try {
                        out.write("### `" + owner + "`\n\n");
                        for (Delta.MethodDelta method : methods) {
                            out.write("- `" + method.name() + method.desc() + "`\n");
                        }
                        out.write("\n");
                    } catch (IOException e) {
                        throw new UncheckedIOException(e);
                    }
                });
            }

            if (!unservable.isEmpty()) {
                out.write("""
                        ### What is Being Listed Here?
                        
                        The diff found no LWJGL 3 method of that name on the class of that name.
                        That is weaker than it reads: the entrypoint may be bound elsewhere under the
                        spelling the extension itself uses, and where it is bound nowhere at all the address
                        can still come from `GL.getFunctionProvider()` and the call from
                        `org.lwjgl.system.JNI`, whose overloads are a fixed but wide set.
                        Both routes have fixed this section once. Check them before concluding a member cannot be
                        served. See `README.md` under "Filling a gap by hand" for where to look.
                        
                        """);
            }

            out.write("""
                    ## Hand-written Method Body
                    
                    LWJGL 3 has a method of the same name, but the signatures do not line up:
                    
                    - Added length parameter
                    - Handle that used to be an object
                    - Return type that changed
                    
                    """);
            if (manual.isEmpty()) {
                out.write("_None._\n\n");
            } else {
                manual.forEach((owner, methods) -> {
                    try {
                        out.write("### `" + owner + "`\n\n");
                        for (Delta.MethodDelta method : methods) {
                            out.write("- `" + method.name() + method.desc() + "`  \n");
                            out.write("  LWJGL 3 offers: " + String.join(", ",
                                    method.candidates().stream().map(c -> "`" + c + "`").toList()) + "\n");
                        }
                        out.write("\n");
                    } catch (IOException e) {
                        throw new UncheckedIOException(e);
                    }
                });
            }

            out.write("""
                    ## Classes with Unvendorable Bodies
                    
                    These exist only in LWJGL 2 and keep their signatures, but their implementations lean on
                    LWJGL 2 internals that LWJGL 3 dropped. The bodies need to be rewritten rather than copied.
                    Every member throws. Listed with what disqualified the original body,
                    which is where writing a replacement starts.
                    
                    Only classes that can be accessible through normal means appear.
                    LWJGL 2's per-platform layer and its nested internals are package-private,
                    so nothing links against them and LWJGLY ships nothing for them.
                    
                    Where the reason is a `native` method, `build/lwjgly/native_calls.md` has the full list
                    for that class and those calls have to be replaced rather than translated.
                    
                    A class drops off this list as soon as one member of it works, so what is left is
                    always work not started. Shims that are written but do less than LWJGL 2 did are
                    further down, under "Technically... Shims...".
                    
                    """);
            if (rewrites.isEmpty()) {
                out.write("_None._\n\n");
            } else {
                rewrites.forEach((owner, reasons) -> {
                    try {
                        out.write("- `" + owner + "`\n");
                        for (String reason : reasons.stream().distinct().limit(4).toList()) {
                            out.write("  - " + reason + "\n");
                        }
                        if (reasons.size() > 4) {
                            out.write("  - ... and " + (reasons.size() - 4) + " more\n");
                        }
                    } catch (IOException e) {
                        throw new UncheckedIOException(e);
                    }
                });
                out.write("\n");
            }

            writeCapabilityGaps(out, lwjgl2, lwjgl3, built);

            out.write("""
                    ## Technically... Shims...
                    
                    These link and return something sensible.
                    These shims either do less or do something slightly different to what LWJGL 2 did.
                    None of them throws.
                    
                    | Member | What it does instead | What it would take |
                    |---|---|---|
                    | `Display.setIcon` | Returns 0, using no icon | Build `SDL_Surface`s from the RGBA buffers, chain by size, `SDL_SetWindowIcon` |
                    | `Display.getAvailableDisplayModes` | Returns only the current mode, so the video settings list has one entry | `SDL_GetFullscreenDisplayModes`, exposed through the window bridge |
                    | `Display.isVisible` | Always true | Track `SDL_EVENT_WINDOW_MINIMIZED` / `_EXPOSED` |
                    | `Display.isDirty` | Always false | Nothing: SDL has no "dirty" flag, and nothing in 1.12.2 reads it(?) |
                    | `Display.setResizable` / `setLocation` / `getX` / `getY` | No-ops and zeroes | `SDL_SetWindowResizable`, `SDL_SetWindowPosition`, `SDL_GetWindowPosition` |
                    | `Display.getPixelScaleFactor` | Always 1 | The framebuffer-to-logical ratio, and mouse coordinates scaled to match |
                    | `Display.setDisplayConfiguration` | No-op | Nothing: SDL 3 dropped gamma ramps |
                    | `Display.create(PixelFormat)` | Ignores the format | Nothing: the context already exists, the host chooses its depth and sample buffers |
                    | `Mouse.isInsideWindow` | Always true | Track `SDL_EVENT_WINDOW_MOUSE_ENTER` / `_LEAVE` |
                    | `Mouse.setClipMouseCoordinatesToWindow` | Remembered, not applied | Nothing: SDL confines the pointer while grabbed, which is the case that matters |
                    
                    These do throw, because there is no sensible answer and nothing on 1.12.2 calls them:
                    `Display.setParent`, `GLContext.useContext`.
                    
                    `Mouse.setNativeCursor` used to be on that list and is now implemented, over SDL's own
                    cursors. One thing it does not do is animate on its own: `Cursor.getCapabilities()`
                    withholds `CURSOR_ANIMATION`, because SDL has no timer for it and the frame only
                    advances when `Display.update()` runs.
                    
                    ## Display.update()
                    
                    `Display.update()` drains the OS event queue, as during the hybrid migration
                    Minecraft's loop is what drives the frame. When Cleanroom's own loop takes over,
                    `Display.update()` has to stop calling it. Two calls do not double events but actually splits
                    them, so half the input disappears into whichever consumer polled first.
                    
                    ## OpenAL is Untested in CI
                    
                    The lifecycle shim (`AL.create`, the `ALC10` overloads taking `ALCdevice`) is checked for
                    linkage but never run: a build machine has no sound device. The first real exercise is
                    paulscode's `librarylwjglopenal` at game start.
                    
                    ## Known Behavioural Differences
 
                    - **Buffer bounds checks.** LWJGL 2's `BufferChecks` threw on an undersized buffer.
                      LWJGL 3 checks only while `Configuration.DISABLE_CHECKS` is off. A mod relying on the
                      exception as control flow gets undefined behaviour instead.
                    - **`glMapBuffer`.** LWJGL 2 inferred the mapped length but LWJGL 3 wants it explicitly.
                      Shims query `GL_BUFFER_SIZE` rather than guessing, which costs a driver round trip.
                    - **Thread Affinity.** LWJGL 2 resolved GL entry points itself and let any thread call
                      in. LWJGL 3 binds them per thread via `GL.setCapabilities()` and throws otherwise.
                      Off-thread GL that happened to work under LWJGL 2 will not.
                    """);
        }
    }


    private static boolean works(Built built, ApiIndex lwjgl3, String owner, Delta.MethodDelta method) {
        return built.classifyMethod(owner, method.name(), method.desc(), lwjgl3).works();
    }

    private static CapabilityFlags.Serviced serviced(ApiIndex lwjgl2, ApiIndex lwjgl3, Built built) {
        return internalName -> {
            ClassNode node = lwjgl2.get(internalName);
            if (node == null) {
                return false;
            }
            return node.methods.stream()
                    .filter(m -> ApiIndex.isCallable(m.access))
                    .filter(m -> m.name.charAt(0) != '<')
                    .map(m -> built.classifyMethod(internalName, m.name, m.desc, lwjgl3))
                    .allMatch(Outcome::works);
        };
    }

    private static Set<String> driverReadFlags(Built built) {
        ClassNode node = built.shims().get("org/lwjgl/opengl/ContextCapabilities");
        Set<String> names = new TreeSet<>();
        if (node == null) {
            return names;
        }
        node.methods.stream()
                .filter(m -> m.name.equals("<init>"))
                .forEach(m -> m.instructions.forEach(insn -> {
                    if (insn instanceof LdcInsnNode ldc && ldc.cst instanceof String flag && flag.startsWith("GL_")) {
                        names.add(flag);
                    }
                }));
        return names;
    }

    private static void writeCapabilityGaps(BufferedWriter out, ApiIndex lwjgl2, ApiIndex lwjgl3, Built built)
            throws IOException {
        CapabilityFlags.Split split = CapabilityFlags.of(lwjgl2, lwjgl3, serviced(lwjgl2, lwjgl3, built));
        if (split.total() == 0) {
            return;
        }

        Set<String> overreached = new TreeSet<>(driverReadFlags(built));
        overreached.retainAll(split.alwaysFalse().keySet());
        if (!overreached.isEmpty()) {
            throw new IllegalStateException("ContextCapabilities reports these extensions present, but not every"
                    + " method on them has a body: " + overreached
                    + " -- finish the shim or the flag will promise calls that throw");
        }

        out.write("## Capability flags that always read false\n\n");
        out.write("`ContextCapabilities` is copied field-for-field from LWJGL 3's `GLCapabilities`, and "
                + split.total() + " of\nLWJGL 2's flags have no counterpart there -- LWJGL 3 dropped the bindings for "
                + "these mostly\nvendor-specific and legacy extensions.\n\n");
        out.write(split.fromDriver().size() + " of those are answered anyway, from the driver's own extension string "
                + "rather than from\n`GLCapabilities`: either the extension declares no methods and the flag is the "
                + "whole feature,\nor its calls are the same calls under a promoted name and a shim forwards them. "
                + "Those\nreport truthfully and are not listed here.\n\n");
        out.write("The " + split.alwaysFalse().size() + " below cannot be. Each has methods LWJGL 3 never bound, and a "
                + "flag reading true is a\npromise about those methods: a mod gated on one has already committed to the "
                + "branch by the\ntime it calls, so reporting the extension present and then throwing is worse than the "
                + "silent\nfallback path. They report false whether or not the driver has them.\n\n");
        for (Map.Entry<String, CapabilityFlags.Blocked> entry : split.alwaysFalse().entrySet()) {
            CapabilityFlags.Blocked blocked = entry.getValue();
            out.write("- `" + entry.getKey() + "` - `" + blocked.className() + "` declares "
                    + blocked.callableMethods() + " method" + (blocked.callableMethods() == 1 ? "" : "s") + "\n");
        }
        out.write("\n");
    }

    private static boolean started(ApiIndex lwjgl2, ApiIndex lwjgl3, Built built, String internalName) {
        ClassNode node = lwjgl2.get(internalName);
        if (node == null) {
            return true;
        }
        List<MethodNode> callable = node.methods.stream()
                .filter(m -> ApiIndex.isCallable(m.access) && m.name.charAt(0) != '<')
                .toList();
        return callable.isEmpty() || callable.stream().anyMatch(m -> built.classifyMethod(internalName, m.name, m.desc, lwjgl3).works());
    }

    private ProblemsDoc() { }

}
